# Generated by Django 4.0.6 on 2022-07-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfc_app', '0002_rename_lattitude_nfc_details_latitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nfc_details',
            name='created_by',
        ),
    ]
